export default {
  INCREMENT: "COUNTER_PLUS",
  DECREMENT: "COUNTER_MINUS",
  STEP_CHANGE: "STEP_CHANGE",
  REQUEST_COUNTER_FETCHING: "REQUEST_COUNTER_FETCHING",
  REQUEST_COUNTER_SUCCESS: "EQUEST_COUNTER_SUCCESS",
  EQUEST_COUNTER_ERROR: "EQUEST_COUNTER_ERROR",
};
