POST http://localhost:5000/api/users/authByQRCode
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQ2NTgwMTZlYTBlNDEyMGU5ZGMwOWUiLCJlbWFpbCI6InJvbGxAZ21haWwuY29tIiwiaWF0IjoxNzYyNDIyNDkzLCJleHAiOjE3NjI0MjYwOTN9.oclHn-vva2f1XvpP0XCzhN8cOT7w-_lm8XTKnIBjzIM"  
}