GET http://localhost:5000/api/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQxM2UxNDVjOWJjYTZiMzNmNTQwNTkiLCJlbWFpbCI6InRhbmlAZ21haWwuY29tIiwiaWF0IjoxNzU4NzIwMTM1LCJleHAiOjE3NTg3MjM3MzV9.hJtRd5i_jtb4vMKsxX9gZvZJJR95CXpf1XaCclb2qnQ