POST http://localhost:5000/api/users/sign-up
Content-Type: application/json

{
    "firstName": "Nataliia",
    "lastName": "Yakovenko",
    "birthday": "1983-07-25",
    "email": "nata@gmail.com",
    "password": "Natali658"
}