POST http://localhost:5000/api/users/registration
Content-Type: application/json

{
    "firstName": "Rem",
    "lastName": "Removich",
    "birthday": "1999-07-25",
    "email": "rem@gmail.com",
    "passwordHash": "Ukraina25"
}