DELETE http://localhost:5000/api/tasks/68dbd682e230ad9f8323c55a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQ2NTgwMTZlYTBlNDEyMGU5ZGMwOWUiLCJlbWFpbCI6InJvbGxAZ21haWwuY29tIiwiaWF0IjoxNzU5MjM3ODcxLCJleHAiOjE3NTkyMzc5OTF9.OpHpfZQupGY7QC30KTKddBgM3XbFmmeR5Dk-8TeCX5M